/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'boys' : null } |
  { 'coLiving' : null } |
  { 'girls' : null };
export type ExternalBlob = Uint8Array;
export interface Hostel {
  'id' : HostelId,
  'name' : string,
  'description' : string,
  'address' : string,
  'ownerContact' : string,
  'category' : Category,
  'imageBlobs' : Array<ExternalBlob>,
  'roomCapacityDetails' : RoomSharing,
}
export type HostelId = bigint;
export interface RoomSharing {
  'sharing1' : bigint,
  'sharing2' : bigint,
  'sharing3' : bigint,
  'sharing4' : bigint,
  'sharing5' : bigint,
  'price1' : bigint,
  'price2' : bigint,
  'price3' : bigint,
  'price4' : bigint,
  'price5' : bigint,
}
export interface UpdateHostelInput {
  'id' : HostelId,
  'roomCapacityDetails' : RoomSharing,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addHostel' : ActorMethod<
    [
      string,
      Category,
      string,
      string,
      RoomSharing,
      Array<ExternalBlob>,
      string,
    ],
    Hostel
  >,
  'getHostel' : ActorMethod<[HostelId], Hostel>,
  'listHostels' : ActorMethod<[], Array<Hostel>>,
  'listHostelsByCategory' : ActorMethod<[Category], Array<Hostel>>,
  'updateHostel' : ActorMethod<[UpdateHostelInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];