/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const RoomSharing = IDL.Record({
  'sharing1' : IDL.Nat,
  'sharing2' : IDL.Nat,
  'sharing3' : IDL.Nat,
  'sharing4' : IDL.Nat,
  'sharing5' : IDL.Nat,
  'price1' : IDL.Nat,
  'price2' : IDL.Nat,
  'price3' : IDL.Nat,
  'price4' : IDL.Nat,
  'price5' : IDL.Nat,
});
export const HostelId = IDL.Nat;
export const Hostel = IDL.Record({
  'id' : HostelId,
  'latitude' : IDL.Float64,
  'isSponsored' : IDL.Bool,
  'imageUrls' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
  'ownerContact' : IDL.Text,
  'category' : IDL.Text,
  'roomCapacityDetails' : RoomSharing,
});
export const UpdateHostelInput = IDL.Record({
  'id' : HostelId,
  'isSponsored' : IDL.Opt(IDL.Bool),
  'roomCapacityDetails' : RoomSharing,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addHostel' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        RoomSharing,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Bool),
      ],
      [Hostel],
      [],
    ),
  'getHostel' : IDL.Func([HostelId], [Hostel], ['query']),
  'getHostelsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Hostel)], ['query']),
  'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
  'listHostels' : IDL.Func([], [IDL.Vec(Hostel)], ['query']),
  'recordVisit' : IDL.Func([], [IDL.Nat], []),
  'updateHostel' : IDL.Func([UpdateHostelInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const RoomSharing = IDL.Record({
    'sharing1' : IDL.Nat,
    'sharing2' : IDL.Nat,
    'sharing3' : IDL.Nat,
    'sharing4' : IDL.Nat,
    'sharing5' : IDL.Nat,
    'price1' : IDL.Nat,
    'price2' : IDL.Nat,
    'price3' : IDL.Nat,
    'price4' : IDL.Nat,
    'price5' : IDL.Nat,
  });
  const HostelId = IDL.Nat;
  const Hostel = IDL.Record({
    'id' : HostelId,
    'latitude' : IDL.Float64,
    'isSponsored' : IDL.Bool,
    'imageUrls' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
    'ownerContact' : IDL.Text,
    'category' : IDL.Text,
    'roomCapacityDetails' : RoomSharing,
  });
  const UpdateHostelInput = IDL.Record({
    'id' : HostelId,
    'isSponsored' : IDL.Opt(IDL.Bool),
    'roomCapacityDetails' : RoomSharing,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addHostel' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          RoomSharing,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Bool),
        ],
        [Hostel],
        [],
      ),
    'getHostel' : IDL.Func([HostelId], [Hostel], ['query']),
    'getHostelsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Hostel)], ['query']),
    'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
    'listHostels' : IDL.Func([], [IDL.Vec(Hostel)], ['query']),
    'recordVisit' : IDL.Func([], [IDL.Nat], []),
    'updateHostel' : IDL.Func([UpdateHostelInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };