/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Category = IDL.Variant({
  'boys' : IDL.Null,
  'coLiving' : IDL.Null,
  'girls' : IDL.Null,
});
export const RoomSharing = IDL.Record({
  'sharing1' : IDL.Nat,
  'sharing2' : IDL.Nat,
  'sharing3' : IDL.Nat,
  'sharing4' : IDL.Nat,
  'sharing5' : IDL.Nat,
  'price1' : IDL.Nat,
  'price2' : IDL.Nat,
  'price3' : IDL.Nat,
  'price4' : IDL.Nat,
  'price5' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const HostelId = IDL.Nat;
export const Hostel = IDL.Record({
  'id' : HostelId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'address' : IDL.Text,
  'ownerContact' : IDL.Text,
  'category' : Category,
  'imageBlobs' : IDL.Vec(ExternalBlob),
  'roomCapacityDetails' : RoomSharing,
});
export const UpdateHostelInput = IDL.Record({
  'id' : HostelId,
  'roomCapacityDetails' : RoomSharing,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addHostel' : IDL.Func(
      [
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Text,
        RoomSharing,
        IDL.Vec(ExternalBlob),
        IDL.Text,
      ],
      [Hostel],
      [],
    ),
  'getHostel' : IDL.Func([HostelId], [Hostel], ['query']),
  'listHostels' : IDL.Func([], [IDL.Vec(Hostel)], ['query']),
  'listHostelsByCategory' : IDL.Func([Category], [IDL.Vec(Hostel)], ['query']),
  'updateHostel' : IDL.Func([UpdateHostelInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Category = IDL.Variant({
    'boys' : IDL.Null,
    'coLiving' : IDL.Null,
    'girls' : IDL.Null,
  });
  const RoomSharing = IDL.Record({
    'sharing1' : IDL.Nat,
    'sharing2' : IDL.Nat,
    'sharing3' : IDL.Nat,
    'sharing4' : IDL.Nat,
    'sharing5' : IDL.Nat,
    'price1' : IDL.Nat,
    'price2' : IDL.Nat,
    'price3' : IDL.Nat,
    'price4' : IDL.Nat,
    'price5' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const HostelId = IDL.Nat;
  const Hostel = IDL.Record({
    'id' : HostelId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'address' : IDL.Text,
    'ownerContact' : IDL.Text,
    'category' : Category,
    'imageBlobs' : IDL.Vec(ExternalBlob),
    'roomCapacityDetails' : RoomSharing,
  });
  const UpdateHostelInput = IDL.Record({
    'id' : HostelId,
    'roomCapacityDetails' : RoomSharing,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addHostel' : IDL.Func(
        [
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Text,
          RoomSharing,
          IDL.Vec(ExternalBlob),
          IDL.Text,
        ],
        [Hostel],
        [],
      ),
    'getHostel' : IDL.Func([HostelId], [Hostel], ['query']),
    'listHostels' : IDL.Func([], [IDL.Vec(Hostel)], ['query']),
    'listHostelsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Hostel)],
        ['query'],
      ),
    'updateHostel' : IDL.Func([UpdateHostelInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };